import images from "../images";

export const categories = [
  {
    name: "Dairy, Bread & Egg",
    url: "Dairy-Bread-&-Egg",
    items: [
      {
        uri: images.Dbe1,
        weight: "200g",
        description: "Milky Mist Paneer",
        price: 100,
      },
      {
        uri: images.Dbe2,
        weight: "500g",
        description: "Amul Mithai Mate Condensed Milk",
        price: 100,
      },
      {
        uri: images.Dbe3,
        weight: "200ml",
        description: "Nandini Toned Fresh Milk",
        price: 100,
      },
      {
        uri: images.Dbe4,
        weight: "500g",
        description: "Amul Pure Milk Cheese Slices",
        price: 100,
      },
      {
        uri: images.Dbe5,
        weight: "200g",
        description: "Amul Salted Butter",
        price: 100,
      },
      {
        uri: images.Dbe6,
        weight: "6 pieces",
        description: "Jaya White Eggs",
        price: 100,
      },
      {
        uri: images.Dbe7,
        weight: "400g",
        description: "Britannia Milk Bread",
        price: 100,
      },
      {
        uri: images.Dbe8,
        weight: "200g",
        description: "Nandini Shubham Pasteurised Standardized Fresh Milk",
        price: 100,
      },
      {
        uri: images.Dbe9,
        weight: "10 pieces",
        description: "Eggoz Farm Fresh White Eggs (10 pieces)",
        price: 100,
      },
      {
        uri: images.Dbe10,
        weight: "500g",
        description: "Amul Blend Diced Cheese",
        price: 100,
      },
      {
        uri: images.Dbe11,
        weight: "400g",
        description: "Britannia Brown Bread",
        price: 100,
      },
    ],
  },
  {
    name: "Rolling paper & tobacoo",
    url: "rolling-paper-and-tobacoo",
    items: [
      {
        uri: images.Rp1,
        weight: "5g",
        description: "Brown Rolling Paper Cones - Stash Pro",
        price: 100,
      },
      {
        uri: images.Rp2,
        weight: "10g",
        description: "Brown Rolling Paper with Roaches - Stash Pro",
        price: 100,
      },
      {
        uri: images.Rp3,
        weight: "12g",
        description:
          "Brown Rolling Paper + Roach with Crushing Tray - Stash Pro",
        price: 100,
      },
      {
        uri: images.Rp4,
        weight: "24g",
        description: "Brown Rolling Paper (King Size) - Stash Pro",
        price: 100,
      },
      {
        uri: images.Rp5,
        weight: "10g",
        description: "White Slim Rolling Paper (King Size) - Elements",
        price: 100,
      },
      {
        uri: images.Rp6,
        weight: "12g",
        description: "Black Organic Hemp Slim Rolling Paper (King Size) - Raw",
        price: 100,
      },
      {
        uri: images.Rp7,
        weight: "21g",
        description: "Black Classic Slim Rolling Paper (King Size) - Raw",
        price: 100,
      },
    ],
  },
  {
    name: "Snacks & Munchies",
    url: "Snacks-&-Munchies",
    items: [
      {
        uri: images.Snacks1,
        weight: "250g",
        description: "Cheetos Cheez Puffs",
        price: 100,
      },
      {
        uri: images.Snacks2,
        weight: "200g",
        description: "Doritos Cheese Nachos",
        price: 100,
      },
      {
        uri: images.Snacks3,
        weight: "15g",
        description: "Lay's American Style Cream & Onion Potato Chips",
        price: 100,
      },
      {
        uri: images.Snacks4,
        weight: "1kg",
        description: "Haldiram's Nagpur Khatta Meetha Namkeen",
        price: 100,
      },
      {
        uri: images.Snacks5,
        weight: "40g",
        description: "Lay's India's Magic Masala Potato Chips (40 g)",
        price: 100,
      },
      {
        uri: images.Snacks6,
        weight: "500g",
        description: "Haldiram's Nagpur Lite Chivda Namkeen",
        price: 100,
      },
      {
        uri: images.Snacks7,
        weight: "1kg",
        description: "Haldiram's Nagpur Aloo Bhujia",
        price: 100,
      },
      {
        uri: images.Snacks8,
        weight: "1kg",
        description: "Haldiram's Nagpur Mixture Namkeen",
        price: 100,
      },
      {
        uri: images.Snacks9,
        weight: "500g",
        description: "Haldiram's Nagpur Mini Bhakarwadi Namkeen",
        price: 100,
      },
      {
        uri: images.Snacks10,
        weight: "2 x 200g",
        description: "Haldiram's Nagpur Salted Fried Peanuts - Pack of 2",
        price: 100,
      },
      {
        uri: images.Snacks11,
        weight: "",
        description: "",
        price: 100,
      },
      {
        uri: images.Snacks12,
        weight: "1kg",
        description: "Haldiram's Nagpur Masala Kaju",
        price: 100,
      },
      {
        uri: images.Snacks13,
        weight: "1kg",
        description: "Haldiram's Nagpur Sev Bhujia",
        price: 100,
      },
      {
        uri: images.Snacks14,
        weight: "2 x 500g",
        description: "Doritos Sweet Chilli Flavour Nachos - Pack of 2",
        price: 100,
      },
      {
        uri: images.Snacks15,
        weight: "2 x 200g",
        description: "Haldiram's Soya Sticks Namkeen - Pack of 2",
        price: 100,
      },
    ],
  },
  {
    name: "Cold Drinks & Juices",
    url: "Cold-Drinks-&-Juices",
    items: [
      {
        uri: images.Drink1,
        weight: "250ml",
        description: "imga1",
        price: 100,
      },
      {
        uri: images.Drink2,
        weight: "200ml",
        description: "paper boat Swing Slurpy Mango Juice",
        price: 100,
      },
      {
        uri: images.Drink3,
        weight: "100ml",
        description: "Monster Energy Drink",
        price: 100,
      },
      {
        uri: images.Drink4,
        weight: "100ml",
        description: "Sting Energy Drink (250 ml)",
        price: 100,
      },
      {
        uri: images.Drink5,
        weight: "500ml",
        description: "paper boat Swing Zesty Pomegranate Juice",
        price: 100,
      },
      {
        uri: images.Drink6,
        weight: "250ml",
        description: "Pepsi Soft Drink ",
        price: 100,
      },
      {
        uri: images.Drink7,
        weight: "250ml",
        description: "Minute Maid Pulpy Orange Fruit Drink",
        price: 100,
      },
      {
        uri: images.Drink8,
        weight: "750ml",
        description: "Thums Up Soft Drink (750 ml)",
        price: 100,
      },
      {
        uri: images.Drink9,
        weight: "2.25 lr",
        description: "Sprite Lime Flavoured Soft Drink (2.25 l)",
        price: 100,
      },
      {
        uri: images.Drink10,
        weight: "500ml",
        description: "paper boat Swing Lush Lychee Juice",
        price: 100,
      },
      {
        uri: images.Drink11,
        weight: "500ml",
        description: "Kinley Soda Water With Extra Punch",
        price: 100,
      },
      {
        uri: images.Drink12,
        weight: "600ml",
        description: "Maaza Mango Drink 600 ml ",
        price: 100,
      },
      {
        uri: images.Drink13,
        weight: "750ml",
        description: "Storia 100% Tender Coconut Water ",
        price: 100,
      },
      {
        uri: images.Drink14,
        weight: "500ml",
        description: "Coca-Cola Soft Drink",
        price: 100,
      },
      {
        uri: images.Drink15,
        weight: "250ml",
        description: "Hamdard Rooh Afza Rose Sharbat",
        price: 100,
      },
    ],
  },
  {
    name: "Candies & Gums",
    url: "Candies-&-Gums",
    items: [
      {
        uri: images.Cg1,
        weight: "14g",
        description: "Impact Sugar Free Mint Candy (Fresh Mints)",
        price: 100,
      },
      {
        uri: images.Cg2,
        weight: "22g",
        description: "Orbit Spearmint Flavour Sugar Free Chewing Gum",
        price: 100,
      },
      {
        uri: images.Cg3,
        weight: "29g",
        description: "Happydent Wave Sugarfree Mint Chewing Gum 18 Pcs ",
        price: 100,
      },
      {
        uri: images.Cg4,
        weight: "14g",
        description: "Impact Sugar Free Mint Candy (Peach)",
        price: 100,
      },
      {
        uri: images.Cg5,
        weight: "12 pieces",
        description: "Wrigley's Hubba Bubba Fruit Flavour Chewing Gum ",
        price: 100,
      },
      {
        uri: images.Cg6,
        weight: "25 pieces",
        description: "Nicotex Mint Nicotine Gum (Sugar Free)",
        price: 100,
      },
      {
        uri: images.Cg7,
        weight: "22g",
        description: "imga1",
        price: 100,
      },
      {
        uri: images.Cg8,
        weight: "",
        description: "imga1",
        price: 100,
      },
      {
        uri: images.Cg9,
        weight: "",
        description: "imga1",
        price: 100,
      },
      {
        uri: images.Cg10,
        weight: "",
        description: "imga1",
        price: 100,
      },
      {
        uri: images.Cg11,
        weight: "",
        description: "imga1",
        price: 100,
      },
      {
        uri: images.Cg12,
        weight: "",
        description: "imga1",
        price: 100,
      },
      {
        uri: images.Cg13,
        weight: "",
        description: "imga1",
        price: 100,
      },
    ],
  },
];
