import images from "../images";

export const categories = [
  {
    name: "Dairy, Bread & Egg",
     images: [
      images.Dbe1,
      images.Dbe2,
      images.Dbe3,
      images.Dbe4,
      images.Dbe5,
      images.Dbe6,
      images.Dbe7,
      images.Dbe8,
      images.Dbe9,
      images.Dbe10,
      images.Dbe12,
      images.Dbe11,
    ],
  },
  {
    name: "Rolling paper & tobacoo",
    images: [
      images.Rp1,
      images.Rp2,
      images.Rp3,
      images.Rp4,
      images.Rp5,
      images.Rp6,
      images.Rp7,
    ],
  },
  {
    name: "Snacks & Munchies",
    images: [
      images.Snacks1,
      images.Snacks2,
      images.Snacks3,
      images.Snacks4,
      images.Snacks5,
      images.Snacks6,
      images.Snacks7,
      images.Snacks8,
      images.Snacks9,
      images.Snacks10,
      images.Snacks11,
      images.Snacks12,
      images.Snacks13,
      images.Snacks14,
      images.Snacks15,
    ],
  },
  {
    name: "Cold Drinks & Juices",
    discription: ["hii", "jhcdiu", "sadniu", "ndkja"],
    images: [
      images.Drink1,
      images.Drink2,
      images.Drink3,
      images.Drink4,
      images.Drink5,
      images.Drink6,
      images.Drink7,
      images.Drink8,
      images.Drink9,
      images.Drink10,
      images.Drink11,
      images.Drink12,
      images.Drink13,
      images.Drink14,
      images.Drink15,
    ],
  },
  {
    name: "Candies & Gums",
    images: [
      images.Cg1,
      images.Cg2,
      images.Cg3,
      images.Cg4,
      images.Cg5,
      images.Cg6,
      images.Cg7,
      images.Cg8,
      images.Cg9,
      images.Cg10,
      images.Cg11,
      images.Cg12,
      images.Cg13,
    ],
  },
];
