import images from "../images";

export const categories = [
  {
    name: "Dairy, Bread & Egg",
    slug: "Dairy-Bread-&-Egg",
    items: [
      {
        uri: images.Dbe1,
        weight: "200g",
        description: "Milky Mist Paneer",
        price: 100,
      },
      {
        uri: images.Dbe2,
        weight: "500g",
        description: "Amul Mithai Mate Condensed Milk",
        price: 100,
      },
      {
        uri: images.Dbe3,
        weight: "200ml",
        description: "Nandini Toned Fresh Milk",
        price: 100,
      },
      {
        uri: images.Dbe4,
        weight: "500g",
        description: "Amul Pure Milk Cheese Slices",
        price: 100,
      },
      {
        uri: images.Dbe5,
        weight: "200g",
        description: "Amul Salted Butter",
        price: 100,
      },
      {
        uri: images.Dbe6,
        weight: "6 pieces",
        description: "Jaya White Eggs",
        price: 100,
      },
      {
        uri: images.Dbe7,
        weight: "400g",
        description: "Britannia Milk Bread",
        price: 100,
      },
      {
        uri: images.Dbe8,
        weight: "200g",
        description: "Nandini Shubham Pasteurised Standardized Fresh Milk",
        price: 100,
      },
      {
        uri: images.Dbe9,
        weight: "10 pieces",
        description: "Eggoz Farm Fresh White Eggs (10 pieces)",
        price: 100,
      },
      {
        uri: images.Dbe10,
        weight: "500g",
        description: "Amul Blend Diced Cheese",
        price: 100,
      },
      {
        uri: images.Dbe11,
        weight: "400g",
        description: "Britannia Brown Bread",
        price: 100,
      },
    ],
  },
  {
    name: "Rolling paper & tobacoo",
    url: "rolling-paper-and-tobacoo",
    items: [
      {
        uri: images.Rp1,
        weight: "5g",
        description: "Brown Rolling Paper Cones - Stash Pro",
        price: 100,
      },
      {
        uri: images.Rp2,
        weight: "10g",
        description: "Brown Rolling Paper with Roaches - Stash Pro",
        price: 100,
      },
      {
        uri: images.Rp3,
        weight: "12g",
        description:
          "Brown Rolling Paper + Roach with Crushing Tray - Stash Pro",
        price: 100,
      },
      {
        uri: images.Rp4,
        weight: "24g",
        description: "Brown Rolling Paper (King Size) - Stash Pro",
        price: 100,
      },
      {
        uri: images.Rp5,
        weight: "10g",
        description: "White Slim Rolling Paper (King Size) - Elements",
        price: 100,
      },
      {
        uri: images.Rp6,
        weight: "12g",
        description: "Black Organic Hemp Slim Rolling Paper (King Size) - Raw",
        price: 100,
      },
      {
        uri: images.Rp7,
        weight: "21g",
        description: "Black Classic Slim Rolling Paper (King Size) - Raw",
        price: 100,
      },
    ],
  },
  {
    name: "Snacks & Munchies",
    url: "Snacks-&-Munchies",
    items: [
      {
        uri: images.Snacks1,
        weight: "250g",
        description: "Cheetos Cheez Puffs",
        price: 100,
      },
      {
        uri: images.Snacks2,
        weight: "200g",
        description: "Doritos Cheese Nachos",
        price: 100,
      },
      {
        uri: images.Snacks3,
        weight: "15g",
        description: "Lay's American Style Cream & Onion Potato Chips",
        price: 100,
      },
      {
        uri: images.Snacks4,
        weight: "1kg",
        description: "Haldiram's Nagpur Khatta Meetha Namkeen",
        price: 100,
      },
      {
        uri: images.Snacks5,
        weight: "40g",
        description: "Lay's India's Magic Masala Potato Chips (40 g)",
        price: 100,
      },
      {
        uri: images.Snacks6,
        weight: "500g",
        description: "Haldiram's Nagpur Lite Chivda Namkeen",
        price: 100,
      },
      {
        uri: images.Snacks7,
        weight: "1kg",
        description: "Haldiram's Nagpur Aloo Bhujia",
        price: 100,
      },
      {
        uri: images.Snacks8,
        weight: "1kg",
        description: "Haldiram's Nagpur Mixture Namkeen",
        price: 100,
      },
      {
        uri: images.Snacks9,
        weight: "500g",
        description: "Haldiram's Nagpur Mini Bhakarwadi Namkeen",
        price: 100,
      },
      {
        uri: images.Snacks10,
        weight: "2 x 200g",
        description: "Haldiram's Nagpur Salted Fried Peanuts - Pack of 2",
        price: 100,
      },
      {
        uri: images.Snacks11,
        weight: "",
        description: "",
        price: 100,
      },
      {
        uri: images.Snacks12,
        weight: "1kg",
        description: "Haldiram's Nagpur Masala Kaju",
        price: 100,
      },
      {
        uri: images.Snacks13,
        weight: "1kg",
        description: "Haldiram's Nagpur Sev Bhujia",
        price: 100,
      },
      {
        uri: images.Snacks14,
        weight: "2 x 500g",
        description: "Doritos Sweet Chilli Flavour Nachos - Pack of 2",
        price: 100,
      },
      {
        uri: images.Snacks15,
        weight: "2 x 200g",
        description: "Haldiram's Soya Sticks Namkeen - Pack of 2",
        price: 100,
      },
    ],
  },
  {
    name: "Cold Drinks & Juices",
    url: "Cold-Drinks-&-Juices",
    items: [
      {
        uri: images.Drink1,
        weight: "250ml",
        description: "imga1",
        price: 100,
      },
      {
        uri: images.Drink2,
        weight: "200ml",
        description: "paper boat Swing Slurpy Mango Juice",
        price: 100,
      },
      {
        uri: images.Drink3,
        weight: "100ml",
        description: "Monster Energy Drink",
        price: 100,
      },
      {
        uri: images.Drink4,
        weight: "100ml",
        description: "Sting Energy Drink (250 ml)",
        price: 100,
      },
      {
        uri: images.Drink5,
        weight: "500ml",
        description: "paper boat Swing Zesty Pomegranate Juice",
        price: 100,
      },
      {
        uri: images.Drink6,
        weight: "250ml",
        description: "Pepsi Soft Drink ",
        price: 100,
      },
      {
        uri: images.Drink7,
        weight: "250ml",
        description: "Minute Maid Pulpy Orange Fruit Drink",
        price: 100,
      },
      {
        uri: images.Drink8,
        weight: "750ml",
        description: "Thums Up Soft Drink (750 ml)",
        price: 100,
      },
      {
        uri: images.Drink9,
        weight: "2.25 lr",
        description: "Sprite Lime Flavoured Soft Drink (2.25 l)",
        price: 100,
      },
      {
        uri: images.Drink10,
        weight: "500ml",
        description: "paper boat Swing Lush Lychee Juice",
        price: 100,
      },
      {
        uri: images.Drink11,
        weight: "500ml",
        description: "Kinley Soda Water With Extra Punch",
        price: 100,
      },
      {
        uri: images.Drink12,
        weight: "600ml",
        description: "Maaza Mango Drink 600 ml ",
        price: 100,
      },
      {
        uri: images.Drink13,
        weight: "750ml",
        description: "Storia 100% Tender Coconut Water ",
        price: 100,
      },
      {
        uri: images.Drink14,
        weight: "500ml",
        description: "Coca-Cola Soft Drink",
        price: 100,
      },
      {
        uri: images.Drink15,
        weight: "250ml",
        description: "Hamdard Rooh Afza Rose Sharbat",
        price: 100,
      },
    ],
  },
  {
    name: "Candies & Gums",
    url: "Candies-&-Gums",
    items: [
      {
        uri: images.Cg1,
        weight: "14g",
        description: "Impact Sugar Free Mint Candy (Fresh Mints)",
        price: 100,
      },
      {
        uri: images.Cg2,
        weight: "22g",
        description: "Orbit Spearmint Flavour Sugar Free Chewing Gum",
        price: 100,
      },
      {
        uri: images.Cg3,
        weight: "29g",
        description: "Happydent Wave Sugarfree Mint Chewing Gum 18 Pcs ",
        price: 100,
      },
      {
        uri: images.Cg4,
        weight: "14g",
        description: "Impact Sugar Free Mint Candy (Peach)",
        price: 100,
      },
      {
        uri: images.Cg5,
        weight: "12 pieces",
        description: "Wrigley's Hubba Bubba Fruit Flavour Chewing Gum ",
        price: 100,
      },
      {
        uri: images.Cg6,
        weight: "25 pieces",
        description: "Nicotex Mint Nicotine Gum (Sugar Free)",
        price: 100,
      },
      {
        uri: images.Cg7,
        weight: "22g",
        description: "imga1",
        price: 100,
      },
      {
        uri: images.Cg8,
        weight: "",
        description: "imga1",
        price: 100,
      },
      {
        uri: images.Cg9,
        weight: "",
        description: "imga1",
        price: 100,
      },
      {
        uri: images.Cg10,
        weight: "",
        description: "imga1",
        price: 100,
      },
      {
        uri: images.Cg11,
        weight: "",
        description: "imga1",
        price: 100,
      },
      {
        uri: images.Cg12,
        weight: "",
        description: "imga1",
        price: 100,
      },
      {
        uri: images.Cg13,
        weight: "",
        description: "imga1",
        price: 100,
      },
    ],
  },
];

export const paancategories = [
  {
    name: "Party essentials",
    url: "Party-essentials",
    items: [
      {
        uri: images.matchbox,
        weight: "5 units",
        description: "Matchbox by Homelites",
        price: 10,
      },
      {
        uri: images.Rp5,
        weight: "1 pack (32 pieces)",
        description: "Black Classic Slim Rolling Paper",
        price: 150,
      },
      {
        uri: images.Rp2,
        weight: "1 unit (32 pieces)",
        description: "Brown Rolling Paper (King Size) - Stash Pro",
        price: 50,
      },
      {
        uri: images.Rp3,
        weight: "i unit",
        description: "Brown Rolling Paper + Roach with Crushing",
        price: 120,
      },
    ],
  },
  {
    name: "Paan corner",
    url: "Paan-corner",
    items: [
      {
        uri: images.matchbox,
        weight: "5 units",
        description: "Matchbox by Homelites",
        price: 10,
      },
      {
        uri: images.Rp5,
        weight: "1 pack (32 pieces)",
        description: "Black Classic Slim Rolling Paper",
        price: 150,
      },
      {
        uri: images.mf1,
        weight: "100gm",
        description: "Chandan Mint Saunf Mouth Freshener",
        price: "41",
      },
      {
        uri: images.Cg2,
        weight: "22gm",
        description: "Orbit Spearmint Flavour Sugar Free Chewingum",
        price: "48",
      },
      {
        uri: images.pc,
        weight: "30.4gm",
        description: "Wrigley's Doublemint Peppermint Candy",
        price: "50",
      },
      {
        uri: images.mf2,
        weight: "100gm",
        description: "Chandan Jeera Goli Digestive Tablets",
        price: "43",
      },
    ],
  },
  {
    name: "Soft Drinks",
    url: "Soft-Drinks",
    items: [
      {
        uri: images.Drink9,
        weight: "750ml",
        description: "Sprite Lime Flavored Soft Drink 750 ml",
        price: "45",
      },
      {
        uri: images.Drink14,
        weight: "750ml",
        description: "Coca-Cola Soft Drink (750 ml)",
        price: "45",
      },
      {
        uri: images.Drink8,
        weight: "750ml",
        description: "Thums Up Soft Drink (750 ml)",
        price: "45",
      },
      {
        uri: images.Drink16,
        weight: "300ml",
        description: "Coca-Cola Zero Sugar Soft Drink",
        price: "40",
      },
      {
        uri: images.Drink6,
        weight: "750ml",
        description: "Pepsi Soft Drink",
        price: "40",
      },
      {
        uri: images.Drink17,
        weight: "250ml",
        description: "7UP Nimbooz with Lemon Juice",
        price: "25",
      },
      {
        uri: images.Drink18,
        weight: "300ml",
        description: "Thums Up Soft Drink (300 ml)",
        price: "40",
      },
      {
        uri: images.Drink19,
        weight: "750",
        description: "Limca Lime 'N' Lemon Soft Drink 750 ml",
        price: "45",
      },
      {
        uri: images.Drink20,
        weight: "300ml",
        description: "Coca-Cola Diet Coke Soft Drink",
        price: "40",
      },
      {
        uri: images.Drink21,
        weight: "600ml",
        description: "Bisleri Limonata Limey Minty Cooler Soft Drink",
        price: "20",
      },
      {
        uri: images.Drink22,
        weight: "750 ml",
        description: "Mirinda Soft Drink",
        price: "40",
      },
      {
        uri: images.Drink23,
        weight: "250ml",
        description: "Pepsi Black Zero Sugar Soft Drink",
        price: "35",
      },
      {
        uri: images.Drink24,
        weight: "300ml",
        description: "oca-Cola Soft Drink",
        price: "40",
      },
      {
        uri: images.Drink25,
        weight: "300 ml",
        description: "Schweppes Ginger Ale",
        price: "59",
      },
      {
        uri: images.Drink26,
        weight: "750 ml",
        description: " 7UP Soft Drink",
        price: "40",
      },
    ],
  },
  {
    name: "Soda & Mixers",
    url: "Soda-&-Mixers",
    items: [
      {
        uri: images.sm1,
        weight: "24 x 250 ml",
        description: "Bisleri Packaged Water - Pack of 24",
        price: " 144",
      },
      {
        uri: images.sm2,
        weight: "750 ml",
        description: "Bisleri Soda Water",
        price: " 20",
      },
      {
        uri: images.sm3,
        weight: " 330 ml",
        description: "Gunsberg ginger Ale",
        price: "99",
      },
      {
        uri: images.Drink11,
        weight: " 750 ml",
        description: "Kinley Soda Water With Extra Punch",
        price: "20",
      },
      {
        uri: images.sm4,
        weight: " 600 ml",
        description: "Lehar Evervess Club Soda Water",
        price: "20",
      },
      {
        uri: images.sm5,
        weight: "500 ml",
        description: " O'cean Mango & Passion Fruit Flavoured Water",
        price: "60",
      },
      {
        uri: images.sm6,
        weight: " 500 ml",
        description: "O'cean Peach & Passion Fruit Flavoured Water",
        price: "60",
      },
      {
        uri: images.sm7,
        weight: "500 ml",
        description: "O'cean Pink Guava Flavoured Water",
        price: "60",
      },
      {
        uri: images.sm8,
        weight: "330 ml",
        description: "Perrier Sparkling Water",
        price: "165",
      },
    ],
  },
  {
    name: "Energy Drinks",
    url: "Energy-Drinks",
    items: [
      {
        uri: images.ed1,
        weight: " 250 ml",
        description: "Red Bull Energy Drink (250 ml)",
        price: "125",
      },
      {
        uri: images.Drink4,
        weight: "      250 ml",
        description: "Sting Energy Drink (250 ml)",
        price: "20",
      },
      {
        uri: images.Drink3,
        weight: " 350 ml",
        description: "Monster Energy Drink",
        price: "122",
      },
      {
        uri: images.ed2,
        weight: " 250 ml",
        description: "Red Bull Energy Drink (Yellow Edition Tropical)",
        price: "125",
      },
      {
        uri: images.ed3,
        weight: "250ml",
        description: "Red Bull Energy Drink (Sugar Free) - 250 ml",
        price: "125",
      },
      {
        uri: images.ed4,
        weight: "350ml",
        description: "Monster Zero Sugar Ultra Energy Drink",
        price: "125",
      },
      {
        uri: images.ed5,
        weight: "250ml",
        description: "Sting Energy Drink",
        price: "35",
      },
    ],
  },
];
